// Write inspect/generated_assets.mbt with the viewer shell and the release
// frontend bundle embedded as MoonBit strings, so a published
// moonbitlang/inspect serves them without any files beside the binary (it runs
// under `moonx`, which fetches a single wasm file). The committed copy of that
// file is empty; scripts/publish.mjs runs this on the staged package only.
//
//   node scripts/embed_inspect_assets.mjs <index.html> <viz_app.js> <output.mbt>
import { readFile, writeFile } from "node:fs/promises";
import { realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";

// A MoonBit multi-line raw string: one `#|` line per source line, joined with
// "\n" and never escaped, so the text round-trips byte for byte. A trailing
// newline becomes a final empty `#|` line. A carriage return would end a `#|`
// line early, so refuse it rather than embed a corrupted asset.
export function mbtRawString(text, indent = "  ") {
  if (text.includes("\r")) {
    throw new Error("cannot embed text containing a carriage return");
  }
  if (text === "") return '""';
  return "\n" + text.split("\n").map(line => `${indent}#|${line}`).join("\n");
}

// The compiler caps how many lines one top-level segment may span, so a large
// asset is split into `///|` segments of this many lines and joined back at
// startup.
const linesPerSegment = 1000;

// One embedded asset as `let <name> : String`, split into numbered part
// segments when it is long. Joining the parts with "\n" restores the text.
export function embeddedStringSource(name, doc, text) {
  const lines = text.split("\n");
  if (lines.length <= linesPerSegment) {
    return ["///|", `/// ${doc}`, `let ${name} : String = ${mbtRawString(text)}`, ""];
  }
  const parts = [];
  const source = [];
  for (let start = 0; start < lines.length; start += linesPerSegment) {
    const part = `${name}_part${parts.length}`;
    parts.push(part);
    const chunk = lines.slice(start, start + linesPerSegment).join("\n");
    source.push("///|", `let ${part} : String = ${mbtRawString(chunk)}`, "");
  }
  source.push(
    "///|",
    `/// ${doc}`,
    `let ${name} : String = [`,
    ...parts.map(part => `  ${part},`),
    '].join("\\n")',
    "",
  );
  return source;
}

export function generatedAssetsSource(indexHtml, bundle) {
  return [
    "// Code generated by scripts/embed_inspect_assets.mjs. DO NOT EDIT.",
    "// The published moonbitlang/inspect carries these; the committed copy of",
    "// this file is empty (see scripts/publish.mjs).",
    "",
    ...embeddedStringSource(
      "embedded_index_html", "The viewer shell (`web/index.html`).", indexHtml,
    ),
    ...embeddedStringSource(
      "embedded_viz_app_js", "The release frontend bundle (`viz_app.js`).", bundle,
    ),
  ].join("\n");
}

export async function embedInspectAssets(indexPath, bundlePath, outputPath) {
  const [indexHtml, bundle] = await Promise.all([
    readFile(indexPath, "utf8"),
    readFile(bundlePath, "utf8"),
  ]);
  if (bundle.trim() === "") throw new Error(`empty bundle: ${bundlePath}`);
  await writeFile(outputPath, generatedAssetsSource(indexHtml, bundle));
  return { indexBytes: indexHtml.length, bundleBytes: bundle.length };
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [indexPath, bundlePath, outputPath] = process.argv.slice(2);
  if (!outputPath) {
    console.error("Usage: node scripts/embed_inspect_assets.mjs <index.html> <viz_app.js> <output.mbt>");
    process.exitCode = 2;
  } else {
    embedInspectAssets(indexPath, bundlePath, outputPath).then(({ indexBytes, bundleBytes }) => {
      console.log(`Embedded ${indexPath} (${indexBytes} chars) and ${bundlePath} (${bundleBytes} chars) into ${outputPath}`);
    }).catch(error => {
      console.error(error.message);
      process.exitCode = 1;
    });
  }
}
